"""empty message

Revision ID: 13eebd5d339
Revises: 3b5f3e97e82
Create Date: 2016-12-28 14:01:22.398745

"""

# revision identifiers, used by Alembic.
revision = '13eebd5d339'
down_revision = '3b5f3e97e82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
