"""empty message

Revision ID: 19271e3179e
Revises: 20552d17f5c
Create Date: 2016-12-29 12:01:19.346644

"""

# revision identifiers, used by Alembic.
revision = '19271e3179e'
down_revision = '20552d17f5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
