"""empty message

Revision ID: 215c00fc3
Revises: 5e24873a7b
Create Date: 2016-12-28 13:13:08.997447

"""

# revision identifiers, used by Alembic.
revision = '215c00fc3'
down_revision = '5e24873a7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
