"""empty message

Revision ID: 53f6751e406
Revises: 4cbcc36d72c
Create Date: 2016-12-29 08:26:02.074451

"""

# revision identifiers, used by Alembic.
revision = '53f6751e406'
down_revision = '4cbcc36d72c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
